import PDFDocument from "pdfkit";

/* =========================================
   GENERATE TIMETABLE PDF (Styled Version)
========================================= */

export const generateTimetablePDF = (entries, res) => {
  try {
    if (!entries || entries.length === 0) {
      return res.status(400).json({
        success: false,
        message: "No timetable data available for PDF export",
      });
    }

    /*
    ===============================
    CREATE DOCUMENT
    ===============================
    */

    const doc = new PDFDocument({
      margin: 40,
      size: "A4",
    });

    res.setHeader("Content-Type", "application/pdf");

    res.setHeader(
      "Content-Disposition",
      "inline; filename=timetable.pdf"
    );

    doc.pipe(res);

    /*
    ===============================
    TITLE SECTION
    ===============================
    */

    doc
      .font("Helvetica-Bold")
      .fontSize(22)
      .fillColor("#1e293b")
      .text("Schedio University Timetable", {
        align: "center",
      });

    doc.moveDown(0.5);

    doc
      .font("Helvetica")
      .fontSize(10)
      .fillColor("#475569")
      .text(
        `Generated At: ${new Date().toLocaleString()}`,
        {
          align: "center",
        }
      );

    doc.moveDown(2);

    /*
    ===============================
    TABLE CONFIG
    ===============================
    */

    const startX = 40;
    let y = doc.y;

    const rowHeight = 28;

    const columnWidths = [
      90,  // Day
      60,  // Slot
      150, // Subject
      140, // Teacher
      90,  // Room
    ];

    const headers = [
      "Day",
      "Slot",
      "Subject",
      "Teacher",
      "Room",
    ];

    /*
    ===============================
    DRAW ROW FUNCTION
    ===============================
    */

    const drawRow = (rowY, rowData, isHeader = false) => {
      let x = startX;

      doc.lineWidth(1);

      rowData.forEach((text, i) => {
        const width = columnWidths[i];

        /*
        CELL BORDER
        */

        doc
          .rect(x, rowY, width, rowHeight)
          .stroke();

        /*
        HEADER STYLE
        */

        if (isHeader) {
          doc
            .font("Helvetica-Bold")
            .fillColor("#0f172a");
        } else {
          doc
            .font("Helvetica")
            .fillColor("#000000");
        }

        /*
        TEXT
        */

        doc.text(
          text,
          x + 5,
          rowY + 8,
          {
            width: width - 10,
            align: "center",
          }
        );

        x += width;
      });
    };

    /*
    ===============================
    HEADER ROW
    ===============================
    */

    drawRow(y, headers, true);

    y += rowHeight;

    /*
    ===============================
    TABLE ROWS
    ===============================
    */

    entries.forEach((entry, index) => {
      const subject =
        entry.subjectId?.name ||
        entry.subjectId?.code ||
        "N/A";

      const teacher =
        entry.teacherId?.name ||
        "N/A";

      const room =
        entry.roomId?.name ||
        "N/A";

      const day =
        entry.day ||
        "N/A";

      const slot =
        entry.slot !== undefined
          ? entry.slot.toString()
          : "-";

      /*
      PAGE BREAK
      */

      if (y + rowHeight > 750) {
        doc.addPage();

        y = 50;

        drawRow(y, headers, true);

        y += rowHeight;
      }

      drawRow(
        y,
        [
          day,
          slot,
          subject,
          teacher,
          room,
        ],
        false
      );

      y += rowHeight;
    });

    /*
    ===============================
    FOOTER
    ===============================
    */

    doc.moveDown(2);

    doc
      .fontSize(9)
      .fillColor("#64748b")
      .text(
        "Generated by Schedio Timetable System",
        {
          align: "center",
        }
      );

    /*
    ===============================
    END DOCUMENT
    ===============================
    */

    doc.end();

  } catch (error) {
    console.error("PDF generation failed:", error);

    if (!res.headersSent) {
      res.status(500).json({
        success: false,
        message: "Failed to generate PDF",
      });
    }
  }
};